# Render.com 部署配置文件
# 这个文件告诉 Render 如何构建和部署您的应用

services:
  - type: web
    name: jizhangben-backend
    env: node
    plan: free
    region: oregon  # 或者选择离您更近的区域
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # 以下环境变量需要在 Render 控制台中手动设置
      # - key: JWT_SECRET
      #   value: your-secret-key
      # - key: SUPABASE_URL
      #   value: your-supabase-url
      # - key: SUPABASE_ANON_KEY
      #   value: your-supabase-anon-key
      # - key: SUPABASE_SERVICE_ROLE_KEY
      #   value: your-service-role-key
      # - key: FRONTEND_URL
      #   value: https://your-frontend-domain.vercel.app

# 可选：如果需要数据库
# databases:
#   - name: jizhangben-db
#     plan: free
#     databaseName: jizhangben
#     user: jizhangben_user